# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'walkandtalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for walkandtalk
  pod 'Firebase/Core', '~> 5.15.0'

  target 'walkandtalk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'walkandtalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'walkandtalk-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for walkandtalk-tvOS

end
