# Generated by Django 2.1.5 on 2019-03-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkandtalk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkingevent',
            name='id',
        ),
        migrations.AlterField(
            model_name='walkingevent',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='walkingevent',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='walkingevent',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
