# Generated by Django 2.1.5 on 2019-03-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkandtalk', '0002_auto_20190303_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkingevent',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='walkingevent',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
