# Generated by Django 2.1.5 on 2019-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkandtalk', '0003_auto_20190303_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkingevent',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
