# Generated by Django 2.1.7 on 2019-03-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walkandtalk', '0005_auto_20190303_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attending', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='walkingevent',
            name='attendee',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkandtalk.WalkingEvent'),
        ),
    ]
