# Generated by Django 2.1.5 on 2019-02-21 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_walkingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='indoor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intensity',
            field=models.CharField(default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='length_of_walk_distance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='length_of_walk_duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='menopause_stage',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
