export const updated_record = {
    id: 2,
    organizer: "User 1",
    fullname: "User 1",
    title: "Another Past Event",
    email: "u1@gmail.com",
    venue: "Indoor",
    date: "Thu, Mar 21",
    start_time: "6:00 pm",
    end_time: "7:30 pm",
    distance: 10,
    duration: 60,
    location: "University of Alberta",
    intensity: "Intermediate",
    walk_rating: "3",
    walk_rating_comment: "",
    location_rating: "3",
    location_rating_comment: "",
    completed: 1,
    total_attendees: 3,
    createdAt: "2019-04-04T18:17:29.552Z",
    updatedAt: "2019-04-04T18:17:29.552Z"

}

export const records = [
    {
        id: 1,
        organizer: "User 1",
        fullname: "User 1",
        title: "Past Event",
        email: "u1@gmail.com",
        venue: "Indoor",
        date: "Thu, Mar 21",
        start_time: "6:00 pm",
        end_time: "7:30 pm",
        distance: null,
        duration: null,
        location: null,
        intensity: "Intermediate",
        walk_rating: null,
        walk_rating_comment: null,
        location_rating: null,
        location_rating_comment: null,
        completed: 0,
        total_attendees: 9,
        createdAt: "2019-04-04T18:17:29.552Z",
        updatedAt: "2019-04-04T18:17:29.552Z"
    },
    {
        id: 2,
        organizer: "User 1",
        fullname: "User 1",
        title: "Another Past Event",
        email: "u1@gmail.com",
        venue: "Indoor",
        date: "Thu, Mar 21",
        start_time: "6:00 pm",
        end_time: "7:30 pm",
        distance: 10,
        duration: 60,
        location: "University of Alberta",
        intensity: "Intermediate",
        walk_rating: "3",
        walk_rating_comment: "",
        location_rating: "3",
        location_rating_comment: "",
        completed: 1,
        total_attendees: 3,
        createdAt: "2019-04-04T18:17:29.552Z",
        updatedAt: "2019-04-04T18:17:29.552Z"
    },
]   

export const completed_records = [
    {
        id: 2,
        organizer: "User 1",
        fullname: "User 1",
        title: "Another Past Event",
        email: "u1@gmail.com",
        venue: "Indoor",
        date: "Thu, Mar 21",
        start_time: "6:00 pm",
        end_time: "7:30 pm",
        distance: 10,
        duration: 60,
        location: "University of Alberta",
        intensity: "Intermediate",
        walk_rating: "3",
        walk_rating_comment: "",
        location_rating: "3",
        location_rating_comment: "",
        completed: 1,
        total_attendees: 3,
        createdAt: "2019-04-04T18:17:29.552Z",
        updatedAt: "2019-04-04T18:17:29.552Z"
    }
]  

export const uncompleted_records = [
    {
        id: 1,
        organizer: "User 1",
        fullname: "User 1",
        title: "Past Event",
        email: "u1@gmail.com",
        venue: "Indoor",
        date: "Thu, Mar 21",
        start_time: "6:00 pm",
        end_time: "7:30 pm",
        distance: null,
        duration: null,
        location: null,
        intensity: "Intermediate",
        walk_rating: null,
        walk_rating_comment: null,
        location_rating: null,
        location_rating_comment: null,
        completed: 0,
        total_attendees: 9,
        createdAt: "2019-04-04T18:17:29.552Z",
        updatedAt: "2019-04-04T18:17:29.552Z"
    }
]   