// TYPES

// USER TYPES
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_EDIT = "USER_EDIT";

// EVENT TYPES
export const SET_EVENTS = "SET_EVENTS";
export const EVENT_CREATE = "EVENT_CREATE";
export const EVENT_DELETE = "EVENT_DELETE";
