// TYPES

// USER TYPES
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_EDIT = "USER_EDIT";
export const PICTURE_EDIT = "PICTURE_EDIT";
export const PICTURE_GET = "PICTURE_GET";
export const SET_USER = "SET_USER";
export const SET_ALL_USERS = "SET_ALL_USERS";
export const USER_APPROVE = "USER_APPROVE";
export const USER_DECLINE = "USER_DECLINE";
export const GET_UNREGISTERED_USERS = "GET_UNREGISTERED_USERS";
export const CLEAR_USER = "CLEAR_USER"

// EVENT TYPES
export const SET_EVENTS = "SET_EVENTS";
export const SET_USER_EVENTS = "SET_USER_EVENTS";
export const EVENT_CREATE = "EVENT_CREATE";
export const EVENT_DELETE = "EVENT_DELETE";
export const EVENT_EDIT = "EVENT_EDIT";

// EVENT RECORD TYPES
export const RECORD_UPDATE = "RECORD_UPDATE";
export const SET_RECORDS = "SET_RECORDS";
export const SET_COMPLETED_RECORDS = "SET_COMPLETED_RECORDS";
export const SET_UNCOMPLETED_RECORDS = "SET_UNCOMPLETED_RECORDS";

// ATTENDEE TYPES
export const ATTENDEE_ADD = "ATTENDEE_CREATE";
export const ATTENDEE_DELETE = "ATTENDEE_DELETE";

// NOTIFICATION TYPES
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_UNREAD_NOTIFICATIONS = "SET_UNREAD_NOTIFICATIONS";
export const NOTIFICATION_CREATE = "NOTIFICATION_CREATE";
export const NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";
