// TYPES

// USER AUTH TYPES
export const AUTH_LOGIN_USER = "AUTH_LOGIN_USER";
export const AUTH_LOGIN_USER_FAIL = "AUTH_LOGIN_USER_FAIL";
export const AUTH_LOGIN_USER_SUCCESS = "AUTH_LOGIN_USER_SUCCESS";
export const AUTH_CREATE_USER = "AUTH_CREATE_USER";
export const AUTH_CREATE_USER_FAIL = "AUTH_CREATE_USER_FAIL";
export const AUTH_CREATE_USER_SUCCESS = "AUTH_CREATE_USER_SUCCESS";

// EVENT TYPES
export const EVENT_FETCH_ALL = "EVENT_FETCH_ALL";
export const EVENT_ADD = "EVENT_ADD";

// PROFILE TYPES
export const PROFILE_FETCH = "PROFILE_FETCH";
export const PROFILE_EDIT = "PROFILE_EDIT";
